version: 2.1

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: "Install Go"
          environment:
            GO_VERSION: "1.24.4"
          command: |
            wget https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
            sudo rm -rf /usr/local/go
            sudo tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
            echo 'export PATH=/usr/local/go/bin:$PATH' >> $BASH_ENV
            go version
      - run:
          name: "Install yq"
          command: |
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq
            yq --version
      - restore_cache:
          keys:
            - v1-go-mod-{{ checksum "go.sum" }}
      - run: make smoke
      - run: make test
      - run: make validate_all
      - store_test_results:
          path: test_results/
      - save_cache:
          key: v1-go-mod-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod

  publish_github:
    docker:
      - image: cibuilds/github:0.13.0
    steps:
      - run:
          name: "Publish Release on GitHub"
          command: |
            echo "Creating GitHub release for tag ${CIRCLE_TAG}"
            ghr -draft -n ${CIRCLE_TAG} -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG}

workflows:
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - publish_github:
          context: Honeycomb Secrets for Public Repos
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9].*/
            branches:
              ignore: /.*/
