name: ToHoneycomb
kind: HoneycombExporter
summary: Export telemetry to Honeycomb in Honeycomb's event format.
description: |
  This component exports telemetry to Honeycomb in Honeycomb's event format.
ports:
  - name: Traces
    direction: input
    type: HoneycombTraces
properties:
  - name: APIKey
    summary: The API key to use to authenticate with Honeycomb
    description: |
      The API key to use to authenticate with Honeycomb.
    type: string
    validations: [nonblank]
    default: ${HONEYCOMB_EXPORTER_APIKEY}
  - name: APIEndpoint
    summary: The Endpoint URL of the Honeycomb API
    description: |
      The Endpoint URL of the Honeycomb API.
      This is normally https://api.honeycomb.io, but can be overridden.
    type: string
    validations: [nonblank, url]
    default: https://api.honeycomb.io
  - name: Compression
    summary: The compression to use when sending data to Honeycomb
    description: |
      The compression to use when sending data to Honeycomb.
      This is normally gzip, but can be overridden.
    type: string
    validations: [nonblank]
    default: gzip
templates:
  - kind: refinery_config
    name: HoneycombExporter_RefineryConfig
    format: dottedConfig
    data:
      - key: Network.HoneycombAPI
        value: "{{ firstNonblank .User.APIEndpoint .Props.APIEndpoint.Default }}"
      - key: AccessKeys.SendKey
        value: "{{ .User.API_Key }}"
  - kind: collector_config
    name: HoneycombExporter_CollectorConfig
    format: dottedConfig
    data:
      - key: exporters.otlphttp.endpoint
        value: "{{ firstNonblank .User.API_URL .Props.API_URL.Default }}"
      - key: exporters.otlphttp.compression
        value: "{{ firstNonblank .User.Compression .Props.Compression.Default }}"
      # TODO: headers must be an array
      - key: exporters.otlphttp.headers
        value:
          - name: x-honeycomb-team
            value: "{{ .User.API_Key }}"
