name: ToHoneycomb
kind: HoneycombExporter
summary: Export telemetry to Honeycomb in Honeycomb's event format.
description: |
  This component exports telemetry to Honeycomb in Honeycomb's event format.
ports:
  - name: Traces
    direction: input
    type: HoneycombTraces
properties:
  - name: APIKey
    summary: The API key to use to authenticate with Honeycomb
    description: |
      The API key to use to authenticate with Honeycomb.
    type: string
    validations: [nonblank]
    default: ${HONEYCOMB_EXPORTER_APIKEY}
  - name: APIEndpoint
    summary: The Endpoint URL of the Honeycomb API
    description: |
      The Endpoint URL of the Honeycomb API.
      This is normally https://api.honeycomb.io, but can be overridden.
    type: string
    validations: [nonblank, url]
    default: https://api.honeycomb.io
templates:
  - kind: refinery_config
    name: HoneycombExporter_RefineryConfig
    format: dotted
    data:
      - key: Network.HoneycombAPI
        value: "{{ firstNonblank .HProps.APIEndpoint .User.APIEndpoint .Props.APIEndpoint.Default }}"
      - key: AccessKeys.SendKey
        value: "{{ firstNonblank .HProps.APIKey .User.APIKey }}"

