name: otel_http_exporter
kind: OTelHTTPExporter
summary: Exports OTLP (OpenTelemetry) traffic via HTTP
description: |
  Exports OpenTelemetry signals using OTLP via HTTP.
ports:
  - name: Traces
    direction: input
    type: OTelTraces
  - name: Metrics
    direction: input
    type: OTelMetrics
  - name: Logs
    direction: input
    type: OTelLogs
properties:
  - name: Host
    summary: The hostname or IP address to send data to
    description: |
      Hostname or IP address on which to send outgoing HTTP traffic.
    type: string
    validations: [nonblank]
    default: https://api.honeycomb.io
  - name: Port
    summary: The port on which to send HTTP traffic.
    description: |
      The port on which to send outgoing HTTP traffic. Default is 443, which is
      the value expected by Honeycomb. The OTel standard for HTTP is 4318.
    type: integer
    validations: [integer]
    default: 443
templates:
  - kind: collector_config
    name: otel_http_exporter_collector
    format: collector
    meta:
      componentSection: exporters
      signalTypes: [traces, metrics, logs] # we'll generate a name for each pipeline if there's more than 1
      collectorComponentName: otlphttp
    data:
      - key: "{{ .ComponentName }}.protocols.http.endpoint"
        value: "{{ firstNonblank .HProps.Host .User.Host .Props.Host.Default }}:{{ firstNonblank .HProps.Port .User.Port .Props.Port.Default }}"
      # service is not part of the template, it's generated automatically by the collectorConfig