name: Basic proxy
description: |
  This is a basic proxy that forwards traces, metrics, and logs from the OpenTelemetry gRPC
  components to the OpenTelemetry exporters. This is useful for testing and debugging, or
  as a starting point for more complex configurations.
components:
  - name: TraceGRPC_1
    kind: TraceGRPC
  - name: OTelTraceExporter_1
    kind: OTelTraceExporter
  - name: MetricsGRPC_1
    kind: MetricsGRPC
  - name: OTelMetricsExporter_1
    kind: OTelMetricsExporter
  - name: LogsGRPC_1
    kind: LogsGRPC
  - name: OTelLogsExporter_1
    kind: OTelLogsExporter
connections:
  - source:
      component: TraceGRPC_1
      port: TraceOut
      type: OTelTraces
    destination:
      component: OTelTraceExporter_1
      port: Traces
      type: OTelTraces
  - source:
      component: MetricsGRPC_1
      port: MetricsOut
      type: OTelMetrics
    destination:
      component: OTelMetricsExporter_1
      port: Metrics
      type: OTelMetrics
  - source:
      component: LogsGRPC_1
      port: LogsOut
      type: OTelLogs
    destination:
      component: OTelLogsExporter_1
      port: Logs
      type: OTelLogs
layout:
  components:
    - name: TraceGRPC_1
      x: 260
      y: 182
    - name: OTelTraceExporter_1
      x: 642
      y: 182
    - name: MetricsGRPC_1
      x: 260
      y: 320
    - name: OTelMetricsExporter_1
      x: 642
      y: 320
    - name: LogsGRPC_1
      x: 260
      y: 460
    - name: OTelLogsExporter_1
      x: 642
      y: 460
